version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: UTC
    labels:
      - dependencies
      - ruby

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: UTC
    labels:
      - dependencies
      - github-actions
