require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/**/*
    - Guardfile

Layout/LineLength:
  Max: 140

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/EmptyBlock:
  Exclude:
    - spec/**/*
    - lib/proforma/services/exporter.rb

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - proforma.gemspec

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - spec/custom_matchers/*

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/custom_matchers/equal_task_spec.rb
