require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from:
  - .rubocop/factory-bot.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/naming.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.0 # for ActiveSupport
  UseCache: True
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'Guardfile'
    # Ignore local files for faster processing
    - 'tmp/**/*'
    - 'out/**/*'
    - 'coverage/**/*'
