name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          CC_TEST_REPORTER_ID: true
        run: bundle exec rspec --color --format progress --require spec_helper

      - name: Send coverage to CodeClimate
        uses: paambaati/codeclimate-action@v3.2.0
        continue-on-error: true
        if: ${{ success() || failure() }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Run rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          filter_mode: nofilter
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rspec:gemfile rubocop-performance:gemfile
          rubocop_flags: --parallel
          reporter: github-check
          skip_install: true
          use_bundler: true
          fail_on_error: true
