name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          CC_TEST_REPORTER_ID: true
        run: bundle exec rspec --color --format progress --require spec_helper

      - name: Send coverage to CodeClimate
        uses: paambaati/codeclimate-action@v3.0.0
        continue-on-error: true
        if: ${{ success() || failure() }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop
